name: Response Time CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  response-time:
    name: Check response time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.38.0
        with:
          command: run-response-time
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
