name: Update Template CI
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-template:
    name: Update from template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.38.0
        with:
          command: run-update-template
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
