name: Uptime CI
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    paths:
      - ".upptimerc.yml"

jobs:
  uptime:
    name: Check uptime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@v1.38.0
        with:
          command: run-uptime
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
